apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations
  template:
    metadata:
      labels:
        service: udaconnect-locations
    spec:
      containers:
      - image: aerosouund/udaconnect-locations-service:latest
        name: udaconnect-locations
        imagePullPolicy: Always
      restartPolicy: Always