apiVersion: v1
kind: Service
metadata:
  labels:
    service: rpc-server
  name: rpc-server
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    service: rpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rpc-server
  name: rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rpc-server
  template:
    metadata:
      labels:
        service: rpc-server
    spec:
      containers:
      - image: aerosouund/rpc-test:latest
        name: rpc-server
        imagePullPolicy: Always
        env:
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_PORT
      restartPolicy: Always